version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.15.5

jobs:
  lint:
    executor:
      name: default
    steps:
    - checkout
    - run: make lint

  test:
    executor:
      name: default
    steps:
    - checkout
    - run: make test

  build-image:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker
    - run: make build-image

workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
      - lint:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
      - build-image:
          requires:
            - test
            - lint
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/

