version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.14.12

jobs:
  lint:
    executor:
      name: default
    steps:
    - checkout
    - run: make lint

  test:
    executor:
      name: default
    steps:
    - checkout
    - run: make test

workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
      - lint:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
