version: 2.1
workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
      - lint:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  test:
    docker:
      - image: docker.io/golang:1.14.12
    steps:
      - checkout
      - run:
          name: Test
          command: make test
  lint:
    docker:
      - image: docker.io/golang:1.14.12
    steps:
      - checkout
      - run:
          name: Lint
          command: make lint
